spring:
  application:
    name: LocaleAPI
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://snackdb.chm9rhbwy6vo.ap-northeast-2.rds.amazonaws.com:3306/snackdb
    username: snackdbuser
    password: snackdbuser

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: org.esnack24.localeapi.food.domain
#
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    com.zaxxer: debug
    org.springframework: info

